#!/bin/sh
set -e

chown -R redis:redis /data /var/log/redis

# first arg is `-f` or `--some-option`
# or first arg is `something.conf`
if [ "${1#-}" != "$1" ] || [ "${1%.conf}" != "$1" ]; then
	set -- redis-server "$@"
fi

if [ "$1" = 'redis-server' ]; then
	if [ ! -f /data/dump.rdb -a ! -z "$REDIS_PASSWORD" ]; then
		sed -i "s/^# requirepass.*$/requirepass $REDIS_PASSWORD/g" /etc/redis.conf
	fi

	if [ "$(id -u)" = '0' ]; then
		set -- su-exec redis "$@"
	fi
fi

exec "$@"
